""" ports

Protocols (ports) for identity application layer.
Application code depends on these protocols, not infra implementations.
"""

from __future__ import annotations

from typing import Any, Protocol


class UserRepositoryPort(Protocol):
    async def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_email(self, *args: Any, **kwargs: Any) -> Any: ...
    async def create(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update(self, *args: Any, **kwargs: Any) -> Any: ...

class TenantRepositoryPort(Protocol):
    async def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_name(self, *args: Any, **kwargs: Any) -> Any: ...
    async def create(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update(self, *args: Any, **kwargs: Any) -> Any: ...

class WorkspaceRepositoryPort(Protocol):
    async def get_by_name(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_by_tenant(self, *args: Any, **kwargs: Any) -> Any: ...

class TenantMembershipRepositoryPort(Protocol):
    async def get(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_tenant(self, *args: Any, **kwargs: Any) -> Any: ...
    async def create(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete(self, *args: Any, **kwargs: Any) -> Any: ...

class WorkspaceMembershipRepositoryPort(Protocol):
    async def get(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_workspace(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    async def create(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete(self, *args: Any, **kwargs: Any) -> Any: ...


class ApiKeyRepositoryPort(Protocol):
    async def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_hash(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_by_workspace(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    async def create(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update(self, *args: Any, **kwargs: Any) -> Any: ...


class UserSessionRepositoryPort(Protocol):
    async def create(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_refresh_hash(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    async def save(self, *args: Any, **kwargs: Any) -> Any: ...
    async def last_seen_for_users(self, *args: Any, **kwargs: Any) -> Any: ...


class IdentityTokenRepositoryPort(Protocol):
    async def get_by_hash(self, *args: Any, **kwargs: Any) -> Any: ...
    async def supersede_pending(self, *args: Any, **kwargs: Any) -> Any: ...
    async def save(self, *args: Any, **kwargs: Any) -> Any: ...


class WorkspaceInvitationRepositoryPort(Protocol):
    async def get_by_hash(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_for_workspace(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_pending_for_email(self, *args: Any, **kwargs: Any) -> Any: ...
    async def save(self, *args: Any, **kwargs: Any) -> Any: ...


class AccountDeletionRequestRepositoryPort(Protocol):
    async def get_pending_for_user(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_due(self, *args: Any, **kwargs: Any) -> Any: ...
    async def save(self, *args: Any, **kwargs: Any) -> Any: ...


class UserMfaRepositoryPort(Protocol):
    async def get_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    async def active_user_ids(self, *args: Any, **kwargs: Any) -> Any: ...
    async def save(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete(self, *args: Any, **kwargs: Any) -> Any: ...


class SavedViewRepositoryPort(Protocol):
    async def list(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_name(self, *args: Any, **kwargs: Any) -> Any: ...
    async def save(self, *args: Any, **kwargs: Any) -> Any: ...
    async def clear_default(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete(self, *args: Any, **kwargs: Any) -> Any: ...


class PinnedObjectRepositoryPort(Protocol):
    async def list(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_target(self, *args: Any, **kwargs: Any) -> Any: ...
    async def save(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete(self, *args: Any, **kwargs: Any) -> Any: ...


class ResourceGrantRepositoryPort(Protocol):
    async def get_by_resource_user(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_by_resource(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_in_scope(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    async def create(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete_by_resource_user(self, *args: Any, **kwargs: Any) -> Any: ...

class ServicePrincipalRepositoryPort(Protocol):
    async def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_by_name(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_all(self, *args: Any, **kwargs: Any) -> Any: ...
    async def create(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete(self, *args: Any, **kwargs: Any) -> Any: ...
