""" ports

Protocols (ports) for identity application layer.
Application code depends on these protocols, not infra implementations.
"""

from __future__ import annotations

from typing import Any, Protocol


class UserRepositoryPort(Protocol):
    def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_email(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...

class TenantRepositoryPort(Protocol):
    def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...

class WorkspaceRepositoryPort(Protocol):
    def get_by_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_by_tenant(self, *args: Any, **kwargs: Any) -> Any: ...

class TenantMembershipRepositoryPort(Protocol):
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_tenant(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...

class WorkspaceMembershipRepositoryPort(Protocol):
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_workspace(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...


class ApiKeyRepositoryPort(Protocol):
    def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_hash(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_by_workspace(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...


class UserSessionRepositoryPort(Protocol):
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_refresh_hash(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    def save(self, *args: Any, **kwargs: Any) -> Any: ...
    def last_seen_for_users(self, *args: Any, **kwargs: Any) -> Any: ...


class AccountDeletionRequestRepositoryPort(Protocol):
    def get_pending_for_user(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_due(self, *args: Any, **kwargs: Any) -> Any: ...
    def save(self, *args: Any, **kwargs: Any) -> Any: ...


class UserMfaRepositoryPort(Protocol):
    def get_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    def active_user_ids(self, *args: Any, **kwargs: Any) -> Any: ...
    def save(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...


class SavedViewRepositoryPort(Protocol):
    def list(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def save(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_default(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...


class PinnedObjectRepositoryPort(Protocol):
    def list(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_target(self, *args: Any, **kwargs: Any) -> Any: ...
    def save(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...


class ResourceGrantRepositoryPort(Protocol):
    def get_by_resource_user(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_by_resource(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_in_scope(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_by_user(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_by_resource_user(self, *args: Any, **kwargs: Any) -> Any: ...
