""" ports

Protocols (ports) for chat application layer.
Application code depends on these protocols, not infrastructure implementations.
"""

from __future__ import annotations

from typing import Protocol, Any, Optional, Sequence

class ConversationRepositoryPort(Protocol):
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def list(self, *args: Any, **kwargs: Any) -> Any: ...
    def soft_delete(self, *args: Any, **kwargs: Any) -> Any: ...

class MessageRepositoryPort(Protocol):
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_by_conversation(self, *args: Any, **kwargs: Any) -> Any: ...
    def count_by_conversation(self, *args: Any, **kwargs: Any) -> Any: ...
