""" ports

Protocols (ports) for appcenter application layer.
Application code depends on these protocols, not infra implementations.
"""

from __future__ import annotations

from typing import Protocol, Any, Optional, Sequence

class AppRepositoryPort(Protocol):
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def list(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...

class AppVersionRepositoryPort(Protocol):
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_by_app(self, *args: Any, **kwargs: Any) -> Any: ...

class AppMarketRepositoryPort(Protocol):
    def list_public(self, *args: Any, **kwargs: Any) -> Any: ...
