import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'

import { expect, test } from '@playwright/test'

import { apiBaseURL, authHeaders, getData, signUpFreshWorkspace } from './helpers'

/**
 * Installing third-party code is the one operation where the trust chain has
 * to hold end to end: a signature verified in a unit test proves the function
 * works, not that the running server enforces it.
 *
 * The fixture is generated by `server/scripts/build_plugin_fixture.py`, and the
 * server under test must trust its key. Without that the suite would be
 * asserting nothing, so it fails loudly rather than skipping.
 */
const fixtureDir =
  process.env.SOIT_PLUGIN_FIXTURE_DIR ||
  path.join(process.env.TEMP || '/tmp', 'plugfix')
const packagePath = path.join(fixtureDir, 'plugin.zip')

function readFixture(): { buffer: Buffer; name: string; version: string } {
  if (!existsSync(packagePath)) {
    throw new Error(
      `Plugin fixture missing at ${packagePath}. Build it with:\n` +
        `  uv run python scripts/build_plugin_fixture.py --out ${fixtureDir}\n` +
        'and start the API with PLUGIN_SIGNATURE_PUBLIC_KEYS set to its key.',
    )
  }
  const keys = JSON.parse(
    readFileSync(path.join(fixtureDir, 'keys.json'), 'utf-8'),
  ) as { name: string; version: string }
  return {
    buffer: readFileSync(packagePath),
    name: keys.name,
    version: keys.version,
  }
}

test('a signed package installs and its tool reaches the capability registry', async ({
  page,
  request,
}) => {
  const fixture = readFixture()
  await signUpFreshWorkspace(page)
  const headers = await authHeaders(page)

  const uploaded = await request.post(`${apiBaseURL}/plugins/package`, {
    headers,
    multipart: {
      package: {
        name: 'plugin.zip',
        mimeType: 'application/zip',
        buffer: fixture.buffer,
      },
    },
  })
  const body = (await uploaded.json()) as {
    data: { plugin?: { id: string }; plugin_id?: string }
    code: string
    message: string
  }
  // The server runs with signatures and digests required, so a pass here means
  // the trust chain held, not that verification was skipped.
  expect(uploaded.ok(), `upload failed: ${body.code} ${body.message}`).toBeTruthy()

  const plugins = await getData<{ items: Array<{ id: string; name: string }> }>(
    request,
    '/plugins?page_size=20',
    headers,
  )
  const installed = plugins.items.find((item) => item.name === fixture.name)
  expect(installed, 'the uploaded plugin should be listed').toBeTruthy()

  const capabilities = await getData<{ items: Array<{ ref?: string; name?: string }> }>(
    request,
    '/plugins/capabilities?page_size=50',
    headers,
  )
  const refs = capabilities.items.map((item) => item.ref || item.name || '')
  // A plugin that installs but exports nothing usable has not really arrived.
  expect(refs.some((ref) => ref.includes('e2e_echo'))).toBeTruthy()
})

test('a tampered package is refused by the running server', async ({ page, request }) => {
  const fixture = readFixture()
  await signUpFreshWorkspace(page)
  const headers = await authHeaders(page)

  // Flip bytes in the middle of the archive: the signature covers the payload
  // digest, so corrupting the payload must invalidate it.
  const tampered = Buffer.from(fixture.buffer)
  const offset = Math.floor(tampered.length / 2)
  tampered[offset] = tampered[offset] ^ 0xff

  const response = await request.post(`${apiBaseURL}/plugins/package`, {
    headers,
    multipart: {
      package: {
        name: 'plugin.zip',
        mimeType: 'application/zip',
        buffer: tampered,
      },
    },
  })

  expect(response.ok()).toBeFalsy()
})

test('a developer cannot install plugin code', async ({ page, request }) => {
  const fixture = readFixture()
  await signUpFreshWorkspace(page)
  const headers = await authHeaders(page)

  // A write-scoped key carries the Dev capability but not governance, which is
  // what separates building agents from widening what they can run.
  const created = await request.post(`${apiBaseURL}/api-keys`, {
    headers,
    data: { name: 'writer', scopes: ['write'], expires_in_days: 30 },
  })
  const key = ((await created.json()) as { data: { api_key: string } }).data.api_key

  const response = await request.post(`${apiBaseURL}/plugins/package`, {
    headers: {
      'X-API-Key': key,
      'X-Workspace-Id': headers['X-Workspace-Id'],
    },
    multipart: {
      package: {
        name: 'plugin.zip',
        mimeType: 'application/zip',
        buffer: fixture.buffer,
      },
    },
  })

  expect(response.status()).toBe(403)
})
