""" ports

Application-layer ports (Protocols) for the pluginmarket module.

Application code depends on these protocols, not on infra implementations.
"""

from __future__ import annotations

from typing import Protocol, Optional, Sequence, Any

from app.modules.pluginmarket.domain.models import Plugin, PluginInstallation


class PluginRepositoryPort(Protocol):
    def get(self, plugin_id: str) -> Optional[Plugin]: ...
    def get_by_name_version(self, name: str, version: str) -> Optional[Plugin]: ...
    def create(self, plugin: Plugin) -> Plugin: ...
    def update(self, plugin: Plugin) -> Plugin: ...
    def delete(self, plugin: Plugin) -> None: ...
    def list(self, published_only: bool = False, limit: int = 100, offset: int = 0) -> Sequence[Plugin]: ...


class PluginInstallationRepositoryPort(Protocol):
    def get(self, installation_id: str) -> Optional[PluginInstallation]: ...
    def get_by_plugin(self, plugin_id: str) -> Optional[PluginInstallation]: ...
    def create(self, installation: PluginInstallation) -> PluginInstallation: ...
    def delete(self, installation: PluginInstallation) -> None: ...
    def list_by_workspace(self, limit: int = 100, offset: int = 0) -> Sequence[PluginInstallation]: ...
